Repository AstralJaeger/NextStop-SWK-2024, pull requests merged in 2024-10, with the labels that each got.

#22 add questions from assignment sheet
  README.md
Labels: documentation

#24 Setup Project Structure
  .idea/.idea.NextStop/.idea/.gitignore
  .idea/.idea.NextStop/.idea/encodings.xml
  .idea/.idea.NextStop/.idea/indexLayout.xml
  .idea/.idea.NextStop/.idea/vcs.xml
  NextStop.Common/Class1.cs
  NextStop.Common/NextStop.Common.csproj
  NextStop.Dal.Ado/Class1.cs
  NextStop.Dal.Ado/NextStop.Dal.Ado.csproj
  NextStop.Dal.Dao/Class1.cs
  NextStop.Dal.Dao/NextStop.Dal.Dao.csproj
  NextStop.Dal.Interface/Class1.cs
  NextStop.Dal.Interface/NextStop.Dal.Interface.csproj
  NextStop.Dal.Simple/Class1.cs
  NextStop.Dal.Simple/NextStop.Dal.Simple.csproj
  NextStop.Domain/Class1.cs
  NextStop.Domain/NextStop.Domain.csproj
  NextStop.Routing/Class1.cs
  NextStop.Routing/NextStop.Routing.csproj
  NextStop.sln
Labels: must have

#25 Chore/test project
  NextStop.Dal.Dao/Class1.cs
  NextStop.Dal.Dao/NextStop.Dal.Dao.csproj
  NextStop.Test/NextStop.Test.csproj
  NextStop.Test/UnitTest1.cs
  NextStop.sln
Labels: testing

#26 Chore/update readme
  README.md
Labels: documentation

#27 Chore/setup docker compose
  .idea/.idea.NextStop/.idea/dataSources.xml
  docker-compose.yaml
Labels: optional

#29 Dev/define datamodel
  DataMoedel.drawio
Labels: documentation
